# Create demographic info and more interpretable labels for SPIDER export data. Creates the following fields:
#   occupation from ccoc2002 codes; 
library(tidyverse)
library(lubridate)

get_demographics <- function(df){
  df_rdy <- df %>% 
    left_join(population, by = 'GEOID') %>%
    # JoAnne says ccoc2002 is unreliable
    mutate(occupation = case_when(ccoc2002 >= 0 & ccoc2002 <= 9 ~ 'Non-Occupational',
                                  ccoc2002 >= 10 & ccoc2002 <= 430 ~ 'Management',
                                  ccoc2002 >= 500 & ccoc2002 <= 950 ~ 'Business and financial operations',
                                  ccoc2002 >= 1000 & ccoc2002 <= 1240 ~ 'Computer and mathematical',
                                  ccoc2002 >= 1300 & ccoc2002 <= 1560 ~ 'Architecture and engineering',
                                  ccoc2002 >= 1600 & ccoc2002 <= 1960 ~ 'Life, physical, and social science',
                                  ccoc2002 >= 2000 & ccoc2002 <= 2060 ~ 'Community and social services',
                                  ccoc2002 >= 2100 & ccoc2002 <= 2150 ~ 'Legal',
                                  ccoc2002 >= 2200 & ccoc2002 <= 2550 ~ 'Education, training, and library',
                                  ccoc2002 >= 2600 & ccoc2002 <= 2960 ~ 'Arts, design, entertainment, sports, and media',
                                  ccoc2002 >= 3000 & ccoc2002 <= 3540 ~ 'Healthcare practitioner and technical',
                                  ccoc2002 >= 3600 & ccoc2002 <= 3650 ~ 'Healthcare support',
                                  ccoc2002 >= 3700 & ccoc2002 <= 3950 ~ 'Protective services',
                                  ccoc2002 >= 4000 & ccoc2002 <= 4160 ~ 'Food preparation and serving-related',
                                  ccoc2002 >= 4200 & ccoc2002 <= 4250 ~ 'Building and grounds cleaning and maintenance',
                                  ccoc2002 >= 4300 & ccoc2002 <= 4650 ~ 'Personal care and service',
                                  ccoc2002 >= 4700 & ccoc2002 <= 4960 ~ 'Sales and related',
                                  ccoc2002 >= 5000 & ccoc2002 <= 5930 ~ 'Office and administrative support',
                                  ccoc2002 >= 6000 & ccoc2002 <= 6130 ~ 'Farming, fishing, and forestry', 
                                  #ccoc2002 == 6050 ~ 'Misc. Agricultural Worker',
                                  ccoc2002 >= 6200 & ccoc2002 <= 6940 ~  'Construction and extraction', 
                                  ccoc2002 >= 7000 & ccoc2002 <= 7620 ~  'Installation, maintenance, and repair',
                                  ccoc2002 >= 7700 & ccoc2002 <= 8960 ~  'Production',
                                  ccoc2002 >= 9000 & ccoc2002 <= 9750 ~  'Transportation and material moving',
                                  ccoc2002 == 9999 ~  'Unknown',
                                  TRUE ~ NA_character_),
           # cstatus is automatically generated by SPIDER - NOTE: rank is not in SPIDER and status is not equal to rank
           status = case_when(cstatus==1 ~ 'Definite',
                              cstatus==2 ~ 'Probable',
                              cstatus==3 ~ 'Possible',
                              cstatus==4 ~ 'Suspicious',
                              cstatus==5 ~ 'Unlikely',
                              cstatus==6 ~ 'Insufficient information',
                              cstatus==7 ~ 'Asymptomatic',
                              cstatus==8 ~ 'Unrelated',
                              cstatus==9 ~ 'Unknown/uncoded',
                              TRUE ~ NA_character_),
           sex = case_when(ccasesex == 'M' ~ 'Male',
                           ccasesex == 'F' ~ 'Female',
                           ccasesex == 'U' ~ 'Unknown'),
           workrel = case_when(cworkrel==1 ~ 'Yes',
                               cworkrel==2 ~ 'Possibly',
                               cworkrel==3 ~ 'No',
                               cworkrel==4 ~ 'Unknown',
                               cworkrel==5 ~ 'N/A',
                               TRUE ~ NA_character_),
           typeexp = case_when(ldrift == TRUE ~ 'Drift',
                               lspray == TRUE ~ 'Spray',
                               lindoorair == TRUE ~ 'Indoor air', 
                               lsurface == TRUE ~ 'Surface', 
                               lcontact == TRUE  ~ 'Contact', 
                               lother == TRUE  ~ 'Other', 
                               lleakspill == TRUE ~ 'Leak or spill', 
                               ltargeted == TRUE ~  'Targeted', 
                               ltypeunk == TRUE ~ 'Unknown',
                               TRUE ~ NA_character_),
           # how will race data work regarding new reporting rules?
           race = case_when(
             ccaserace == 1 ~ 'American Indian, Alaskan Native',
             ccaserace == 2 ~ 'Asian or Pacific Islander',
             ccaserace == 3 ~ 'Black',
             ccaserace == 5 ~ 'White',
             ccaserace == 6 ~ 'Mixed Race',
             ccaserace == 8 ~ 'Other, Brown',
             ccaserace == 9 ~ 'Unknown',
             TRUE ~ NA_character_),
           hisp = case_when(
             ccasehisp == 1 ~ 'Yes',
             ccasehisp == 2 ~ 'No',
             ccasehisp == 9 ~ 'Unknown',
           ),
           crop = case_when(ctarget == 10 ~ 'Landscape or ornamental',
                            ctarget == 20 ~ 'Forest trees',
                            ctarget == 31 ~ 'Veterinary/livestock',
                            ctarget == 32 ~ 'Veterinary/domestic animals',
                            ctarget >= 41 & ctarget <= 43 ~ 'Buildings',
                            ctarget == 50 ~ 'Weeds/undesired plants',
                            ctarget >= 60 & ctarget <= 61 ~ 'Pools',
                            ctarget == 70 ~ 'Soil',
                            ctarget == 80 ~ 'Wood products',
                            ctarget >= 100 & ctarget <= 120 ~ 'Fruit crops',
                            ctarget == 200 ~ 'Beverage crops', 
                            ctarget == 300 ~ 'Flavoring and spice crops', 
                            ctarget >= 400 & ctarget <= 460 ~ 'Miscellaneous vegetables', 
                            ctarget >= 500 & ctarget <= 550 ~ 'Grains, grasses, and fiber crops', 
                            ctarget >= 600 & ctarget <= 601 ~ 'Oils crops and seed treatments'),
           product_class = case_when(class1 == 1 ~ 'Organochlorine compound',
                                     class1 == 2 ~ 'Organophosphorous compound',
                                     class1 == 3 ~ 'N-methyl carbamates',
                                     class1 == 4 ~ 'Pyrethrin',
                                     class1 == 5 ~ 'Pyrethroid',
                                     class1 == 6 ~ 'Dipyridyl compound',
                                     class1 == 7 ~ 'Chlorophenoxy compound',
                                     class1 == 8 ~ 'Triazines',
                                     class1 == 9 ~ 'Thiocarbamates',
                                     class1 == 10 ~ 'Organo-mettalic compounds',
                                     class1 == 11 ~ 'Inorganic compounds',
                                     class1 == 12 ~ 'Coumarins',
                                     class1 == 13 ~ 'Indandiones',
                                     class1 == 14 ~ 'Convulsants',
                                     class1 == 15 ~ 'Microbial',
                                     class1 == 16 ~ 'Dithiocarbamates',
                                     class1 == 17 ~ 'AChE inhibitors (comb. of OC and OP only)',
                                     class1 == 18 ~ 'AChE inhibitors w/ pyrethrin and/or pyrethroid only',
                                     class1 == 19 ~ 'AChE inhibitors w/ pyrethrin and/or pyrethroid + other',
                                     class1 == 20 ~ 'AChE inhibitors w/ OC only',
                                     class1 == 21 ~ 'AChE inhibitors w/ compounds not otherwise listed',
                                     class1 == 22 ~ 'Pytrethrin plus pyrethroid only',
                                     class1 == 23 ~ 'Pytrethrin plus pyrethroid plus other compounds not otherwise specified',
                                     class1 == 24 ~ 'Inorganic plus organometallic compounds only',
                                     class1 == 25 ~ 'OC plus inorganic compounds',
                                     class1 == 26 ~ 'Pyrethrin plus other compounds not otherwise specified',
                                     class1 == 94 ~ 'GMO',
                                     class1 == 95 ~ 'Unidentified cholinesterase inhibitor',
                                     class1 == 96 ~ 'Other',
                                     class1 == 97 ~ 'Multiple (not otherwise specified)',
                                     class1 == 99 ~ 'Unknown',
                                     TRUE ~ NA_character_),
           # functional class (pesticide type)
           func_class = case_when(type1 == 1 ~ 'Insecticide',
                                  type1 == 2 ~ 'Insect Growth Regulator',
                                  type1 == 3 ~ 'Herbicide/Algicide',
                                  type1 == 4 ~ 'Fungicide',
                                  type1 == 5 ~ 'Fumigant',
                                  type1 == 6 ~ 'Rodenticide',
                                  type1 == 7 ~ 'Disinfectant/Broad Spectrum for Water Sanitation',
                                  type1 == 8 ~ 'Insect Repellent',
                                  type1 == 9 ~ 'Antifouling Agent',
                                  type1 >= 10 & type1 <= 14 | type1 == 97 ~ 'Multiple',
                                  type1 == 96 ~ 'Other',
                                  TRUE ~ NA_character_),
           # revised groupings by ACH
           county_group = case_when(
             # 1 = North Sound ACH
             county == 'Whatcom' ~ 1,
             county == 'Skagit' ~ 1,
             county == 'Island' ~ 1,
             county == 'San Juan' ~ 1,
             # 2 = Olympic Community of Health
             county == 'Clallam' ~ 2,
             county == 'Jefferson' ~ 2,
             county == 'Grays Harbor' ~ 3, #2
             county == 'Mason' ~ 3, #2
             county == 'Kitsap' ~ 2,
             # 3 = Cascade Pacific Action Alliance
             county == 'Pacific' ~ 3,
             county == 'Lewis' ~ 3,
             county == 'Cowlitz' ~ 3,
             # 4 = SWACH
             county == 'Clark' ~ 4, #3
             county == 'Wahkiakum' ~ 3,
             county == 'Skamania' ~ 4,
             # 5 = Greater Columbia ACH
             county == 'Yakima' ~ 5, #4
             county == 'Klickitat' ~ 5,# 4
             county == 'Chelan' ~ 6, #4
             county == 'Kittitas' ~ 5,
             # 6 = North Central ACH
             county == 'Douglas' ~ 6, #5
             county == 'Okanogan' ~ 6,
             # 7 = Better Health Together
             county == 'Ferry' ~ 7, # 6
             county == 'Stevens' ~ 7, #6
             county == 'Pend Oreille' ~ 7, #6
             county == 'Benton' ~ 5, # 7
             county == 'Franklin' ~ 5, #7
             county == 'Walla Walla' ~ 5, #7, 
             county == 'Columbia' ~ 5, #7,
             county == 'Garfield' ~ 5, #7 
             county == 'Asotin' ~ 5, #7
             county == 'Snohomish' ~ 1, #8
             # 8 = Healthier Here
             county == 'King' ~ 8, #8
             # 9 = Elevate Health
             county == 'Pierce' ~ 9, #
             county == 'Thurston' ~ 3, #8,
             county == 'Grant' ~ 6, #9,
             county == 'Adams' ~ 7, #9
             county == 'Whitman' ~ 5, #9
             county == 'Spokane' ~ 7, #9
             county == 'Lincoln' ~ 7, #9
             county == 'Unknown' ~ 10)) #10 
  return(df_rdy)}